# see https://s.apache.org/asfyaml
github:
  description: "Apache Maven Doxia Sitetools"
  homepage: https://maven.apache.org/doxia/doxia-sitetools
  labels:
    - java
    - build-management
    - apache-maven
    - maven
    - doxia
  protected_branches:
    master: { }
  pull_requests:
    del_branch_on_merge: true
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: true
  autolink_jira:
    - DOXIASITETOOLS
  features:
    issues: true
notifications:
  commits: commits@maven.apache.org
  issues: issues@maven.apache.org
  pullrequests: issues@maven.apache.org
